# Generated by Django 4.2.13 on 2024-08-23 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_activation_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+7 (705) 723 8447'. Up to 15 digits allowed.", regex='^\\+?1?\\d{1,4}?[\\s\\-\\(\\)]*\\d{1,4}?[\\s\\-\\(\\)]*\\d{1,4}?[\\s\\-\\(\\)]*\\d{1,4}?[\\s\\-\\(\\)]*\\d{1,9}$')]),
        ),
    ]
