# Generated by Django 5.0.4 on 2024-06-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_student_grade_alter_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('parent', 'Parent'), ('supervisor', 'Supervisor')], max_length=15, null=True),
        ),
    ]
