# Generated by Django 4.2.13 on 2024-09-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher'), ('supervisor', 'Supervisor')], max_length=15, null=True),
        ),
    ]
