# Generated by Django 5.0.3 on 2024-03-17 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_school_city_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
