# Generated by Django 5.0.4 on 2024-06-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_child_grade_alter_class_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('kz', 'Kazakh'), ('en', 'English')], default='ru', max_length=50),
        ),
        migrations.AddField(
            model_name='class',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('kz', 'Kazakh'), ('en', 'English')], default='ru', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('kz', 'Kazakh'), ('en', 'English')], default='ru', max_length=50),
        ),
    ]
