# Generated by Django 4.2.13 on 2024-07-19 23:49

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_student_birth_date_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_token_expires_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 20, 23, 49, 1, 494289), null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_token_expires_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 20, 23, 49, 1, 494313), null=True),
        ),
    ]
