# Generated by Django 5.0.4 on 2024-05-06 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_student_school_alter_teacher_school'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tasks.league'),
        ),
        migrations.AddField(
            model_name='child',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='tasks.league'),
        ),
        migrations.AddField(
            model_name='student',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
