# Generated by Django 5.0.4 on 2024-05-10 06:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
