# Generated by Django 5.0.4 on 2024-05-19 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_remove_class_teacher_rename_xp_child_cups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='league',
        ),
        migrations.RemoveField(
            model_name='student',
            name='league',
        ),
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
