# Generated by Django 5.0.4 on 2024-05-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_remove_child_league_remove_student_league_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('superuser', 'Superuser'), ('student', 'Student'), ('parent', 'Parent'), ('staff', 'Staff')], max_length=15, null=True),
        ),
    ]
