# Generated by Django 5.0.4 on 2024-05-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_task_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
