# Generated by Django 5.0.4 on 2024-05-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_student_last_task_completed_at_student_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(unique=True)),
                ('cups_required', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='last_task_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='child',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
