# Generated by Django 5.0.4 on 2024-05-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_child_birth_date_child_gender_student_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='school',
        ),
    ]
