# Generated by Django 4.2.13 on 2024-07-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.CharField(choices=[('free-trial', 'Free Trial'), ('monthly', 'Monthly'), ('6-month', '6 Month'), ('annual', 'Annual')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
