# Generated by Django 4.2.13 on 2024-08-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_payment_invoice_id_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='duration',
            field=models.CharField(choices=[('free-trial', 'Free Trial'), ('monthly', 'Monthly'), ('6-month', '6 Month'), ('annual', 'Annual')], default='annual', max_length=10),
            preserve_default=False,
        ),
    ]
