# Generated by Django 4.2.13 on 2024-08-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_payment_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
