# Generated by Django 5.0.4 on 2024-05-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_xp', models.PositiveIntegerField(default=0)),
                ('max_xp', models.PositiveIntegerField(default=100)),
            ],
        ),
    ]
