# Generated by Django 5.0.4 on 2024-06-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.TextField(default='Helloo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(default=';wlkd;wkd', max_length=255),
            preserve_default=False,
        ),
    ]
