# Generated by Django 5.0.4 on 2024-05-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='max_xp',
        ),
        migrations.RemoveField(
            model_name='league',
            name='min_xp',
        ),
        migrations.AddField(
            model_name='league',
            name='xp_threshold',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
