# Generated by Django 4.2.13 on 2024-07-24 21:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_activation_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskcompletion',
            unique_together={('user', 'task'), ('child', 'task')},
        ),
    ]
