# Generated by Django 5.0.4 on 2024-05-06 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_child_league_child_xp_student_league_student_xp'),
        ('tasks', '0002_remove_league_max_xp_remove_league_min_xp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('MCQ', 'Multiple-Choice Questions'), ('DD', 'Drag and Drop'), ('FIB', 'Fill-in-the-Blanks'), ('TF', 'True or False'), ('SA', 'Short Answer'), ('SO', 'Sorting and Ordering')], max_length=3)),
                ('description', models.TextField()),
                ('xp_reward', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to='account.child')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to='account.student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tasks.task')),
            ],
        ),
    ]
