# Generated by Django 5.0.4 on 2024-06-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_lesson_description_remove_lesson_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('task', 'Task'), ('lesson', 'Lesson')], default='task', max_length=10),
            preserve_default=False,
        ),
    ]
