# Generated by Django 4.2.13 on 2024-08-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_content_section_chapter_content_chapter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
    ]
