# Generated by Django 5.0.4 on 2024-06-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('drag_and_drop', 'Drag and Drop'), ('true_false', 'True or False'), ('mark_all', 'Mark All That Apply'), ('number_line', 'Number Line'), ('drag_position', 'Drag Position')], max_length=50),
        ),
    ]
