# Generated by Django 5.0.4 on 2024-05-06 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_child_league_child_xp_student_league_student_xp'),
        ('tasks', '0003_task_taskcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='data',
            field=models.TextField(default='Hel', help_text='Stores task-specific data in JSON format'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TaskResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_responses', to='account.child')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_responses', to='account.student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='tasks.task')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskCompletion',
        ),
    ]
