# Generated by Django 5.0.4 on 2024-06-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='type',
            new_name='content_type',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='text',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice_text', 'Multiple Choice Text'), ('multiple_choice_images', 'Multiple Choice Images'), ('drag_and_drop', 'Drag and Drop'), ('true_false', 'True or False'), ('mark_all', 'Mark All That Apply'), ('number_line', 'Number Line'), ('drag_position', 'Drag Position')], max_length=50),
        ),
    ]
