# Generated by Django 5.0.4 on 2024-05-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_xp_threshold_league_max_xp_league_min_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresponse',
            name='is_true',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
