# Generated by Django 4.2.13 on 2025-03-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_question_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('modo', 'MODO'), ('ent', 'ENT')], default='regular', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.IntegerField(choices=[(-1, '-1'), (0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
    ]
