# Generated by Django 5.0.4 on 2024-06-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_type_content_content_type_remove_lesson_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.IntegerField(db_index=True),
        ),
    ]
