# Generated by Django 4.2.19 on 2025-03-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_course_course_type_alter_course_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('regular', 'Regular')], default='regular', max_length=50),
        ),
    ]
