# Generated by Django 5.0.4 on 2024-06-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_course_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
