# Generated by Django 5.0.4 on 2024-05-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskresponse_is_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='xp_reward',
            field=models.PositiveIntegerField(choices=[(10, '10 XP'), (20, '20 XP'), (30, '30 XP'), (40, '40 XP'), (50, '50 XP')]),
        ),
    ]
