# Generated by Django 5.0.4 on 2024-05-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_answer_taskcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
