# Generated by Django 5.0.4 on 2024-06-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcompletion',
            name='wrong',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
