# Generated by Django 5.0.4 on 2024-06-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_content_description_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(default='djqlqwd', max_length=255),
            preserve_default=False,
        ),
    ]
