# Generated by Django 5.0.4 on 2024-06-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_section_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order']},
        ),
    ]
