# Generated by Django 5.0.4 on 2024-06-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_section_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['grade']},
        ),
    ]
