# Generated by Django 5.0.4 on 2024-06-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_course_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='content',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
