# Generated by Django 5.0.4 on 2024-06-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_remove_lesson_video_url_content_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='template',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
