# Generated by Django 5.0.4 on 2024-06-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_question_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='template',
            field=models.CharField(blank=True, default='1', max_length=20, null=True),
        ),
    ]
