# Generated by Django 5.0.4 on 2024-06-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_alter_question_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='option_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
