# Generated by Django 5.0.4 on 2024-06-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_image_option_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice_text', 'Multiple Choice Text'), ('multiple_choice_images', 'Multiple Choice Images'), ('drag_and_drop_text', 'Drag and Drop Text'), ('drag_and_drop_images', 'Drag and Drop Images'), ('true_false', 'True or False'), ('mark_all', 'Mark All That Apply'), ('number_line', 'Number Line'), ('drag_position', 'Drag Position')], max_length=50),
        ),
    ]
