# Generated by Django 4.2.13 on 2024-07-24 07:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_user_activation_token_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0023_course_language_alter_course_grade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('user', 'question'), ('child', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='taskcompletion',
            unique_together={('user', 'child', 'task')},
        ),
    ]
