# Generated by Django 4.2.13 on 2025-03-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='grade',
            field=models.IntegerField(choices=[(-1, '-1'), (0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True),
        ),
    ]
