# Generated by Django 4.2.13 on 2025-03-10 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
