# Generated by Django 5.0.3 on 2024-03-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_school_city_student_gpa_teacher_subject_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('principal', 'Principal'), ('admin', 'Admin')], max_length=15, null=True),
        ),
    ]
