# Generated by Django 5.0.4 on 2024-05-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_user_email_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='xp',
            new_name='cups',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='xp',
            new_name='cups',
        ),
        migrations.RemoveField(
            model_name='child',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='school',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='child',
            name='stars',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='stars',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('parent', 'Parent'), ('staff', 'Staff')], max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
