# Generated by Django 5.0.4 on 2024-05-21 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_levelrequirement_child_last_task_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='account.parent'),
        ),
    ]
